### ISSUE TITLE
How to do Sparsity + Finetuning

### ISSUE THREAD

**Issue by Thunderbeee** [vllm-project/llm-compressor#1028]
hi the team, thanks so much for your works!

We found the performance was not good after simply pruning, so we want to do finetuing after pruning (as this example https://github.com/vllm-project/llm-compressor/tree/main/examples/quantization_2of4_sparse_w4a16 but **without** quantization).

Could you please give us an example of achieve Sparsity + Finetuning, and load the final model with vLLM or Huggingface? Thanks!

**Comment by dsikka** [comment]
Hi @Thunderbeee, 

The recipe in the example you listed can be updated to only apply sparsity + finetune:
```yaml
sparsity_stage:
  run_type: oneshot
  sparsity_modifiers:
    SparseGPTModifier:
      sparsity: 0.5
      mask_structure: "2:4"
      sequential_update: false
finetuning_stage:
  run_type: train
  finetuning_modifiers:
    ConstantPruningModifier:
      targets: [
        're:.*q_proj.weight',
        're:.*k_proj.weight', 
        're:.*v_proj.weight',
        're:.*o_proj.weight',
        're:.*gate_proj.weight',
        're:.*up_proj.weight',
        're:.*down_proj.weight',
      ]
      start: 0
```

You can then run the same apply(...) call as in the example, while adding one additional argument, `save_compressed=False`, e.g.:

```python
apply(
    model=model,
    dataset=dataset,
    recipe=recipe,
    bf16=bf16,
    output_dir=output_dir,
    splits=splits,
    max_seq_length=max_seq_length,
    num_calibration_samples=num_calibration_samples,
    num_train_epochs=num_train_epochs,
    logging_steps=logging_steps,
    save_steps=save_steps,
    gradient_checkpointing=gradient_checkpointing,
    learning_rate=learning_rate,
    lr_scheduler_type=lr_scheduler_type,
    warmup_ratio=warmup_ratio,
    save_compressed=False
)
```
The model produced should then generate coherent results. 
The following model was generated using the above code and can then run using transformers:

```python

MODEL_ID = 'llm-compressor/examples/quantization_2of4_sparse_w4a16/output_llama7b_2of4_w4a16_channel/stage_finetuning'

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID, device_map="auto", torch_dtype="auto"
)
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

input_ids = tokenizer("The Toronto Raptors are", return_tensors="pt").input_ids.to("cuda")
output = model.generate(input_ids, max_new_tokens=30)
print(tokenizer.decode(output[0]))
```

Output:
```bash
<s> The Toronto Raptors are a professional basketball team based in Toronto, Canada.</s>
````
