### ISSUE TITLE
Does llmcompressor support hybrid sparsity?

### ISSUE THREAD

**Issue by jiangjiadi** [vllm-project/llm-compressor#1037]
**Is your feature request related to a problem? Please describe.**
I've found that the model's performance is constrained when 2:4 sparsity is applied to all linear layers. However, the performance improves significantly when only some layers are subjected to 2:4 sparsity. 

**Describe the solution you'd like**
Does llmcompressor support this hybrid compression format? Specifically, compressing the linear layers that satisfy 2:4 sparsity in the 2:4 format, and compressing the other linear layers that do not meet the 2:4 sparsity criteria using the standard quantization format.

**Comment by rahul-tuli** [comment]
Hi @jiangjiadi, 

Thank you for raising this question and for your interest in **llm-compressor**! The short answer is yes—**llm-compressor** does support a hybrid compression approach, enabling you to apply 2:4 sparsity to certain layers while using standard quantization for others. 

The key to achieving this lies in the configuration of your recipe. Below is an example of how such a recipe might look:

```yaml
pruning_stage:
    obcq_modifiers:
        SparseGPTModifier:
            sparsity: 0.5
            sequential_update: true
            mask_structure: "2:4"
            targets: ['re:model.layers.1.*$'] # Applies 2:4 sparsity to the first layer

quant_stage:
    quant_modifiers:
        QuantizationModifier:
            ignore: ["lm_head"] # Excludes specific layers from quantization
            scheme: "FP8_DYNAMIC"
            targets: ["Linear"] # Applies quantization to all linear layers

    pruning_modifiers:
        ConstantPruningModifier:
            targets: [
                're:.*q_proj.weight',
                're:.*k_proj.weight', 
                're:.*v_proj.weight',
                're:.*o_proj.weight',
                're:.*gate_proj.weight',
                're:.*up_proj.weight',
                're:.*down_proj.weight',
            ]
            start: 0 # Ensures sparsity is retained during quantization
```

### Key Notes:
1. **Flexible Targeting:** The `targets` and `ignore` attributes in the recipe allow fine-grained control, enabling you to specify which layers should be subjected to sparsity, quantization, or both.
2. **Important Caveat:** Any layer targeted for both 2:4 sparsity and quantization must also be included in the `ConstantPruningModifier`. This ensures the induced sparsity is preserved during the quantization process and avoids any unintended conflicts.

Feel free to experiment with these configurations or let us know if you encounter any issues while implementing this setup. We're here to help!
