### ISSUE TITLE
Performance (reproducible) Issue

### ISSUE THREAD

**Issue by Thunderbeee** [vllm-project/llm-compressor#1058]
Hi the team! Thanks so much for your works. I follow the instruction provided in https://github.com/vllm-project/llm-compressor/issues/1028, but the final accuracy is not desirable. I use ultrachat as the dataset, and test on MMLU.
  
<img width="419" alt="Screenshot 2025-01-10 at 11 31 03 PM" src="https://github.com/user-attachments/assets/fe5c43fb-82c9-4778-841e-70539edf3a59" />

However, from Huggingface https://huggingface.co/neuralmagic/Sparse-Llama-3.1-8B-2of4, we can found the Accuracy Recovery is extremely high. I am wondering how to reproduce the result you claimed officially. Thanks!

**Comment by kylesayrs** [comment]
Hi @Thunderbeee,

The models in your table do not match the model you linked to (your table references `llama3.2-1b-instruct` and `gemma-2b`, but the model you linked to is from the `llama-3.1-8B` base model)

Achieving accuracy recovery after intensive compression (both sparsification and quantization) for small models (<8B) is often very difficult. 1B and 2B models are already extremely parameter efficient, so compressing these models will affect accuracy more than compressing larger models, which typically have less parameter efficiency and therefore more capability for compression.

**Comment by kylesayrs** [comment]
If yours is a TinyML application and requires small models, I would recommend focusing on fine tuning your model to your specific task/domain and evaluating on that task. I would not expect compressed (especially fine-tuned) 1B models to perform well on generalized tasks such as MMLU.

**Comment by Thunderbeee** [comment]
Thank you kylesayrs! I get it. I found sparsity + distillation may achieve a better result. Hence, I follow the example in trl_mixin/ex_trl_distillation.py, and change recipe to 

```
recipe = """
test_stage:
  pruning_modifiers:
    SparseGPTModifier:
      sparsity: 0.5
      mask_structure: "2:4"
      sequential_update: false
    OutputDistillationModifier:
      targets: ['re:model.layers.\\d+$']
      comparison: "square_head"
      start: 0
      orig_scale: 1.0
      distill_scale: 1.0
"""
```

but it could not perform SparseGPTModifier.

Could you please provide an instruction how to perform SparseGPT + Distillation? and explain why ConstantPruningModifier works but SparseGPTModifier does not?

Thanks so much!
