### ISSUE TITLE
Fail when faulty recipes are provided during `oneshot`

### ISSUE THREAD

**Issue by dsikka** [vllm-project/llm-compressor#1225]
**Describe the bug**
- Invalid recipes should throw an error 

- Currently, the following recipe is accepted as a valid recipe, however, the `group_0` key should be under `config_groups`
```yaml
quant_stage:
  quant_modifiers:
    GPTQModifier:
      ignore: ["lm_head"]
      group_0:
        weights:
          num_bits: 4
          type: "int"
          symmetric: true
          strategy: "group"
          group_size: 128
          actorder: "group"
          observer: "mse"
        targets: ["Linear"]
```

**Expected behavior**
- Throw a clear error letting the user know their provided recipe is invalid
- Indicate the issue in the provided recipe
