### ISSUE TITLE
How to specify activation quantization method in yaml version receipt?

### ISSUE THREAD

**Issue by zjnyly** [vllm-project/llm-compressor#1242]
I want to try W5A8 quantization. However, I can't simply write like this
```
GPTQModifier(targets="Linear", scheme="W5A8", ignore=["lm_head"]),
```
But if I write a yaml version receipt, I don't know where to specify the quantization method for activation. I want to achieve dynamic W5A8 quantization. Thanks!
```
quantization_stage:
  run_type: oneshot
  quantization_modifiers:
    GPTQModifier:
      ignore: ["lm_head"]
      config_groups:
        group_0:
          weights:
            num_bits: 4
            type: "int"
            symmetric: true
            strategy: "group"
            group_size: 128
          targets: ["Linear"]
```

**Comment by dsikka** [comment]
Hi @zjnyly, you can specify the activations in a few ways:

For the  recipe, you can extend it by adding an "activations" block to you yaml file:

```yaml
quant_stage:
  quant_modifiers:
    GPTQModifier:
      ignore: [lm_head]
      config_groups:
        group_0:
          weights: {num_bits: 8, type: int, symmetric: true, strategy: group, group_size: 128}
          input_activations: {num_bits: 8, type: int, symmetric: true, strategy: tensor}
          targets: [Linear]
```

Other examples can be found here: https://github.com/vllm-project/llm-compressor/tree/main/tests/e2e/vLLM/recipes/INT8

You can also provide a recipe directly made up of the QuantizationScheme and QuantizationArgs:

```python

recipe = QuantizationModifier(
    targets="Linear",
    ignore=["lm_head"],
    config_groups={
        "group_0": QuantizationScheme(
            targets=["Linear"],
            weights=QuantizationArgs(
                num_bits=8,
                symmetric=True,
                strategy=QuantizationStrategy.GROUP,
                group_size=128,
                observer="mse"
            ),
            input_activations=QuantizationArgs(
                num_bits=8,
                type=QuantizationType.INT,
                strategy=QuantizationStrategy.TENSOR,
                symmetric=True,
                dynamic=False,
                observer=None,
            ),
        )
    },
)

```

For more details:
https://github.com/neuralmagic/compressed-tensors/blob/main/src/compressed_tensors/quantization/quant_scheme.py
