### ISSUE TITLE
Inference for sparse model not supported?

### ISSUE THREAD

**Issue by yzlnew** [vllm-project/llm-compressor#45]
**Describe the bug**
Generate a 2:4 sparse model using following yaml,

```
sparsity_stage:
  run_type: oneshot
  sparsity_modifiers:
    SparseGPTModifier:
      sparsity: 0.5
      mask_structure: "2:4"
      sequential_update: true
```

but fail to inference using vLLM 0.5.3.

```
ValueError: Unknown quantization method
``` 

**Expected behavior**
An example to run semi structured sparse model, utilizing the compress-tensors format
