### ISSUE TITLE
RuntimeError: prob_m = 59136 is not divisible by thread_m = 512 when performing inference Qwen2-72B with marlin24

### ISSUE THREAD

**Issue by yzlnew** [vllm-project/llm-compressor#54]
**Describe the bug**
Can't inference a Qwen2-72B 2:4 sparse and GPTQ model using vLLM.
Should I manually lower the thread_m to 256 to fix the shape mismatch?

**To Reproduce**
Exact steps to reproduce the behavior:

```yaml
sparsity_stage:
  run_type: oneshot
  sparsity_modifiers:
    SparseGPTModifier:
      sparsity: 0.5
      mask_structure: "2:4"
      sequential_update: true
quantization_stage:
  run_type: oneshot
  quantization_modifiers:
    GPTQModifier:
      sequential_update: true
      ignore: ["lm_head"]
      config_groups:
        group_0:
          weights:
            num_bits: 4
            type: "int"
            symmetric: true
            strategy: "channel"
          targets: ["Linear"]
```

and inference using `vLLM 0.5.3.post1`.

**Errors**
`RuntimeError: prob_m = 59136 is not divisible by thread_m = 512`

**Additional context**
Add any other context about the problem here. Also include any relevant files.
